name: Workflow
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "2.6"
          - "2.5"
          - "jruby-9.1.9.0"
        gemfile:
          - "gemfiles/rails_5.2_no_sprockets.gemfile"
          - "gemfiles/rails_5.2_no_sprockets_webpacker_3.gemfile"
          - "gemfiles/rails_5.2_no_sprockets_webpacker_4.gemfile"
          - "gemfiles/rails_5.2_sprockets_3.gemfile"
          - "gemfiles/rails_5.2_sprockets_4.gemfile"
        exclude:
          - ruby: "2.6"
          - ruby: "2.5"
          - ruby: "jruby-9.1.9.0"
        include:
          - ruby: "2.6"
            gemfile: gemfiles/rails_5.2_no_sprockets_webpacker_4.gemfile
          - ruby: "2.6"
            gemfile: gemfiles/rails_5.2_sprockets_4.gemfile
          - ruby: "2.5"
            gemfile: gemfiles/rails_5.2_no_sprockets_webpacker_4.gemfile
          - ruby: "2.5"
            gemfile: gemfiles/rails_5.2_sprockets_4.gemfile
          - ruby: jruby-9.1.9.0
            gemfile: gemfiles/rails_5.2_no_sprockets_webpacker_4.gemfile
            old: true
          - ruby: jruby-9.1.9.0
            gemfile: gemfiles/rails_5.2_sprockets_4.gemfile
            old: true
    steps:
      - uses: actions/checkout@v2
      - run: "sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg"
      - run: >-
          echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee
          /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -y -qq yarn
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        continue-on-error: ${{ matrix.old }}
      - run: gem update --system
        continue-on-error: ${{ matrix.old }}
      - run: >-
          google-chrome-stable --headless --disable-gpu
          --remote-debugging-port=9222 http://localhost &
        continue-on-error: ${{ matrix.old }}
